name: CICD
on: push
jobs:
  compile_job:
    runs-on: ubuntu-latest
    steps:
      - name: Compiling My Java App
        run: |
          pwd
          ls
          echo "Hello world"

  test_job:
    needs: compile_job
    runs-on: ubuntu-latest
    steps:
      - name: Testing our java app
        run: echo "Running the Tests"

  package_job:
    needs: test_job
    runs-on: ubuntu-latest
    steps:
      - name: Deploying Tests
        run: echo "Packaging our java app for deployment"